name: reveal js tests

on:
  push:
    paths:
      # Include this workflow
      - '.github/workflows/ci.revealjs.yml'
      # Include target folder
      - 'teacher-docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./teacher-docs

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ${{ env.working-directory }}
    - run: npm run build --if-present
      working-directory: ${{ env.working-directory }}
    - run: npm test
      working-directory: ${{ env.working-directory }}
      env:
        CI: true
